### ISSUE TITLE
Update to the "Recent Friend Updates" panel

### ISSUE THREAD

**Issue by Exablade** [cicerakes/DarkNight-MyAnimeList#15]
- **Browser:** Firefox 104.0.2
- **Links to pages where the issue occurs:**
- https://myanimelist.net/ (if the "Recent Friend Updates" panel is enabled)
- https://myanimelist.net/history/USERNAME/updates (it has to be your own username and you probably need friends as well otherwise the page is going to be empty)

**Describe the problem**
Announcement: https://myanimelist.net/forum/?topicid=2047835
The new elements introduced with the update weren't affected by the theme, this is what I added to fix the issue:

```css
body.index .widget-container .widget.friend_list_updates .image,
.history_content_wrapper .history-updates .image {
    border-color: #3e3e3e;
}
body.index .widget-container .widget.friend_list_updates.right .item:not(:last-child),
.history_content_wrapper .history-updates .item:not(:last-child) .body {
    border-bottom-color: #3e3e3e;
}
body.index .widget-container .widget.friend_list_updates .notes,
.history_content_wrapper .history-updates .notes {
    background-color: #272727;
}
body.index .widget-container .widget.friend_list_updates .notes-btn:hover,
body.index .widget-container .widget.friend_list_updates .navi-btn:hover,
body.index .widget-container .widget.friend_list_updates .footer .btn-settings,
body.index .widget-container .widget.friend_list_updates .footer .link-more,
.history_content_wrapper .history-updates .notes-btn:hover,
.history_content_wrapper .history-updates .navi-btn:hover {
    color: #5378cb;
}
body.index .widget-container .widget.friend_list_updates .footer {
    border-top-color: #3e3e3e;
    background-color: #272727;
}
.history_content_wrapper .history-updates .work-graph {
    background-color: #262626;
    border-color: #3e3e3e;
}
.history_content_wrapper .history-updates .wrok-graph-inner.watching,
.history_content_wrapper .history-updates .wrok-graph-inner.reading {
    background-color: #50c35b;
}
.history_content_wrapper .history-updates .work-status-num.watching,
.history_content_wrapper .history-updates .work-status-num.reading {
    color: #50c35b;
}
.history_content_wrapper .history-updates .wrok-graph-inner.completed {
    background-color: #3d5dad;
}
.history_content_wrapper .history-updates .work-status-num.completed {
    color: #3d5dad;
}
.history_content_wrapper .history-updates .wrok-graph-inner.on-hold {
    background-color: #f6d874;
}
.history_content_wrapper .history-updates .work-status-num.on-hold {
    color: #f5de8f;
}
.history_content_wrapper .history-updates .wrok-graph-inner.dropped {
    background-color: #ba4b4d;
}
.history_content_wrapper .history-updates .work-status-num.dropped {
    color: #ba4b4d;
}
/* "comment" box */
.mal-modal .mal-modal-dialog .mal-modal-content,
.mal-modal .mal-modal-dialog .mal-modal-content .mal-modal-body .modal-profile-comment-form{
    background-color: #1e1e1e;
    color: #cecece;
}
.mal-modal .mal-modal-dialog .mal-modal-content .mal-modal-header {
    border-bottom-color: #3e3e3e;
}
.mal-modal .mal-modal-dialog .mal-modal-content .mal-modal-body .modal-profile-comment-quote {
    background-color: #272727;
    color: #787878;
}
.mal-modal .mal-modal-dialog .mal-modal-content button.btn-close {
    color: #cecece;
}
```
"wrok" is not a mistake, MAL spelled it that way; there's also no "re-watching/reading" class)
