### ISSUE TITLE
MAL updated the forums

### ISSUE THREAD

**Issue by Exablade** [cicerakes/DarkNight-MyAnimeList#16]
- **Browser:** Firefox 105.0.3
- **Links to pages where the issue occurs:**
- [Announcement thread](https://myanimelist.net/forum/?topicid=2052554)
- [Episode discussion example](https://myanimelist.net/forum/?topicid=341951)

**Describe the problem**
They updated the forum and a lot of things are now white again.
Some CSS I added to fix the issue on my end, I hope I found everything:
```css
/* forum threads, right column */
.page-forum .forum-topic-message .message-wrapper .content {
	background-color: #1e1e1e;
	border: 1px solid #444444;
}
/* forum threads, left column */
.page-forum .forum-topic-message .message-wrapper .profile {
	background-color: #252525;
	border: 1px solid #444444;
}
/* navbar, buttons */
.mal-navbar {
	--mal-navbar-bg-color: #272727;
}
a.mal-btn.secondary, button.mal-btn.secondary {
	--mal-btn-text-color: #cecece;
	--mal-btn-bg-color: #1e1e1e;
	--mal-btn-border-color: #5d5d5d;
	--mal-btn-highlight-text-color: #cecece;
	--mal-btn-highlight-bg-color: #373737;
	--mal-btn-highlight-border-color: #373737;
	--mal-btn-outline-text-color: #5d5d5d;
	--mal-btn-outline-bg-color: #1e1e1e;
	--mal-btn-outline-border-color: #3e3e3e;
	--mal-btn-outline-highlight-text-color: #5d5d5d;
	--mal-btn-outline-highlight-bg-color: rgba(37,37,37,.1);
	--mal-btn-outline-highlight-border-color: #4a4a4a;
	--mal-btn-separator-color: #1e1e1e;
}
/* quick reply box */
.page-common .topic-reply-box {
	background-color: #272727;
}
/* quick reply cancel button */
a.mal-btn, button.mal-btn {
	--mal-btn-outline-bg-color: #1e1e1e;
	--mal-btn-separator-color: #1e1e1e;
}
/* quick reply arrow thing */
.page-common .topic-reply-box::before {
	border-bottom: 12px solid #272727;
}
/* "1 post has been added since your last page refresh" alert */
.mal-alert.info {
	--mal-alert-bg-color: #121c30;
}
/* new quote menu when highlighting text */
div.mal-tipmenu a {
    color:#fff !important;
}
/* episode threads */
.page-forum .topic-poll .topic-poll-result .topic-poll-option .vote .topic-poll-button {
	background-color: #1e1e1e;
	border: 1px solid #2e51a2;
	color: #5378cb;
}
div.mal-alert.danger {
	color: #000;
}
```
