### ISSUE TITLE
BBCode toolbar update

### ISSUE THREAD

**Issue by Exablade** [cicerakes/DarkNight-MyAnimeList#17]
- **Browser:** Firefox 107.0.1
- **Link to page where the issue occurs:** https://myanimelist.net/forum/?topicid=2065303

**Describe the problem**
They updated the forum UI again which added a BBCode toolbar. Existing CSS doesn't support it so I added the following lines on my end to fix the issue:
```css
.sceditor-container {
	background: #1e1e1e;
	border-color: #3e3e3e;
	color: #ccc;
}
div.sceditor-toolbar {
	background: #262626;
	border-bottom-color: #3F3F3F;
}
div.sceditor-group:not(:last-child) {
	border-right-color: #444444;
}
.sceditor-button div::before {
	color:  #CDCDCD;
}
.sceditor-button:hover, .sceditor-button:active, .sceditor-button.active {
	background: #444444;
}
/* edit: I replaced "body > p" with "p", let me know if it breaks anything */
p, .sceditor-container iframe, .sceditor-container textarea, html {
	background: #1e1e1e;
	color: #cecece;
}
code, blockquote, blockquote.spoiler {
	background-color: #1e1e1e;
	border-color: #444444;
}
blockquote cite {
	color: #5378cb;
}
```
